const db=require('../config/database');
class Engagement {
 static id(p='eng'){return `${p}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;}
 static async toggle(table,userId,comicId){ if(!['comic_likes','comic_follows'].includes(table))throw new Error('Invalid engagement'); if(db.isPgConnected()){const check=await db.query(`SELECT 1 FROM ${table} WHERE user_id=$1 AND comic_id=$2`,[userId,comicId]);if(check.rowCount){await db.query(`DELETE FROM ${table} WHERE user_id=$1 AND comic_id=$2`,[userId,comicId]);return false;}await db.query(`INSERT INTO ${table}(id,user_id,comic_id) VALUES($1,$2,$3)`,[this.id('eng'),userId,comicId]);return true;}db.fallbackStore[table]??=[];const a=db.fallbackStore[table],i=a.findIndex(x=>x.user_id===userId&&x.comic_id===comicId);if(i>=0){a.splice(i,1);db.saveFallbackStore();return false;}a.push({id:this.id('eng'),user_id:userId,comic_id:comicId,created_at:new Date()});db.saveFallbackStore();return true; }
 static async state(table,userId,comicId){if(db.isPgConnected()){const r=await db.query(`SELECT 1 FROM ${table} WHERE user_id=$1 AND comic_id=$2`,[userId,comicId]);return !!r.rowCount;}return !!(db.fallbackStore[table]||[]).some(x=>x.user_id===userId&&x.comic_id===comicId);}
 static async list(table,userId){if(db.isPgConnected()){const r=await db.query(`SELECT c.* FROM comics c JOIN ${table} e ON e.comic_id=c.id WHERE e.user_id=$1 ORDER BY e.created_at DESC`,[userId]);return r.rows;}const ids=(db.fallbackStore[table]||[]).filter(x=>x.user_id===userId).map(x=>x.comic_id);return db.fallbackStore.comics.filter(c=>ids.includes(c.id));}
 static async followers(comicId){if(db.isPgConnected()){const r=await db.query('SELECT user_id FROM comic_follows WHERE comic_id=$1',[comicId]);return r.rows.map(x=>x.user_id);}return (db.fallbackStore.comic_follows||[]).filter(x=>x.comic_id===comicId).map(x=>x.user_id);}
 static async count(table,comicId){if(db.isPgConnected()){const r=await db.query(`SELECT COUNT(*)::int AS count FROM ${table} WHERE comic_id=$1`,[comicId]);return r.rows[0].count;}return (db.fallbackStore[table]||[]).filter(x=>x.comic_id===comicId).length;}
 static async rate(userId,comicId,rating,review=''){if(rating<1||rating>5)throw new Error('Rating must be between 1 and 5.');if(db.isPgConnected()){await db.query(`INSERT INTO ratings(id,user_id,comic_id,rating,review) VALUES($1,$2,$3,$4,$5) ON CONFLICT(user_id,comic_id) DO UPDATE SET rating=EXCLUDED.rating,review=EXCLUDED.review,updated_at=CURRENT_TIMESTAMP`,[this.id('rating'),userId,comicId,rating,String(review||'').slice(0,2000)]);await db.query('UPDATE comics SET rating=COALESCE((SELECT AVG(rating) FROM ratings WHERE comic_id=$1),0) WHERE id=$1',[comicId]);return;}db.fallbackStore.ratings??=[];const a=db.fallbackStore.ratings,x=a.find(r=>r.user_id===userId&&r.comic_id===comicId);if(x){x.rating=rating;x.review=review;x.updated_at=new Date();}else a.push({id:this.id('rating'),user_id:userId,comic_id:comicId,rating,review,created_at:new Date()});const rs=a.filter(r=>r.comic_id===comicId),c=db.fallbackStore.comics.find(c=>c.id===comicId);if(c)c.rating=rs.reduce((n,v)=>n+Number(v.rating),0)/rs.length;db.saveFallbackStore();}
 static async comments(comicId){if(db.isPgConnected()){const r=await db.query(`SELECT c.*,u.username,u.avatar,(SELECT COUNT(*) FROM comment_likes cl WHERE cl.comment_id=c.id)::int AS like_count FROM comments c JOIN users u ON u.id=c.user_id WHERE c.comic_id=$1 AND c.status='visible' ORDER BY c.created_at DESC`,[comicId]);return r.rows;}return (db.fallbackStore.comments||[]).filter(c=>c.comic_id===comicId&&(c.status||'visible')==='visible').sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));}
 static async comment(userId,comicId,text,parentCommentId=null){if(!text||text.trim().length<1||text.length>2000)throw new Error('Comment must be 1-2000 characters.');const id=this.id('comment');if(db.isPgConnected()){const r=await db.query(`INSERT INTO comments(id,user_id,comic_id,body,parent_comment_id) VALUES($1,$2,$3,$4,$5) RETURNING *`,[id,userId,comicId,text.trim(),parentCommentId||null]);return r.rows[0];}db.fallbackStore.comments??=[];const c={id,user_id:userId,comic_id:comicId,body:text.trim(),parent_comment_id:parentCommentId||null,status:'visible',like_count:0,created_at:new Date()};db.fallbackStore.comments.push(c);db.saveFallbackStore();return c;}
 static async deleteComment(id,userId,isAdmin=false){if(db.isPgConnected()){const r=await db.query(isAdmin?'UPDATE comments SET status=\'deleted\',updated_at=CURRENT_TIMESTAMP WHERE id=$1':'UPDATE comments SET status=\'deleted\',updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND user_id=$2',isAdmin?[id]:[id,userId]);return !!r.rowCount;}const c=db.fallbackStore.comments.find(x=>x.id===id);if(!c||(!isAdmin&&c.user_id!==userId))return false;c.status='deleted';c.updated_at=new Date();db.saveFallbackStore();return true;}
 static async likeComment(userId,commentId){if(db.isPgConnected()){const c=await db.query('SELECT 1 FROM comments WHERE id=$1 AND status=\'visible\'',[commentId]);if(!c.rowCount)return false;const q=await db.query('SELECT 1 FROM comment_likes WHERE user_id=$1 AND comment_id=$2',[userId,commentId]);if(q.rowCount){await db.query('DELETE FROM comment_likes WHERE user_id=$1 AND comment_id=$2',[userId,commentId]);return false;}await db.query('INSERT INTO comment_likes(id,user_id,comment_id) VALUES($1,$2,$3)',[this.id('clike'),userId,commentId]);return true;}db.fallbackStore.comment_likes??=[];const a=db.fallbackStore.comment_likes,i=a.findIndex(x=>x.user_id===userId&&x.comment_id===commentId);if(i>=0){a.splice(i,1);db.saveFallbackStore();return false;}a.push({id:this.id('clike'),user_id:userId,comment_id:commentId,created_at:new Date()});db.saveFallbackStore();return true;}
 static async listFollowingCreators(userId){if(db.isPgConnected()){const r=await db.query('SELECT u.id,u.username,u.avatar FROM users u JOIN creator_follows cf ON cf.creator_id=u.id WHERE cf.follower_id=$1 ORDER BY cf.created_at DESC',[userId]);return r.rows;}const ids=(db.fallbackStore.creator_follows||[]).filter(x=>x.follower_id===userId).map(x=>x.creator_id);return db.fallbackStore.users.filter(u=>ids.includes(u.id)).map(({password_hash,...u})=>u);}
 static async toggleCreatorFollow(followerId,creatorId){if(followerId===creatorId)return false;if(db.isPgConnected()){const q=await db.query('SELECT 1 FROM users WHERE id=$1 AND role IN (\'creator\',\'admin\')',[creatorId]);if(!q.rowCount)throw new Error('Creator not found.');const c=await db.query('SELECT 1 FROM creator_follows WHERE follower_id=$1 AND creator_id=$2',[followerId,creatorId]);if(c.rowCount){await db.query('DELETE FROM creator_follows WHERE follower_id=$1 AND creator_id=$2',[followerId,creatorId]);return false;}await db.query('INSERT INTO creator_follows(id,follower_id,creator_id) VALUES($1,$2,$3)',[this.id('cfollow'),followerId,creatorId]);return true;}db.fallbackStore.creator_follows??=[];const a=db.fallbackStore.creator_follows,i=a.findIndex(x=>x.follower_id===followerId&&x.creator_id===creatorId);if(i>=0){a.splice(i,1);db.saveFallbackStore();return false;}a.push({id:this.id('cfollow'),follower_id:followerId,creator_id:creatorId,created_at:new Date()});db.saveFallbackStore();return true;}
}
module.exports=Engagement;
