const Feature=require('../services/featureService');
const User=require('../models/User');
const Comic=require('../models/Comic');
const Email=require('../services/emailService');
class FeatureController {
 static async track(req,res,next){try{await Feature.analytics({userId:req.user?.id||null,eventType:req.body.eventType,path:req.body.path||req.originalUrl,comicId:req.body.comicId||null,chapterId:req.body.chapterId||null,metadata:req.body.metadata||{},ip:req.ip});res.status(204).end();}catch(e){next(e)}}
 static async overview(req,res,next){try{res.json(await Feature.overview(req.query.days||30));}catch(e){next(e)}}
 static async report(req,res,next){try{const row=await Feature.createReport({reporterId:req.user.id,...req.body});res.status(201).json({report:row,message:'Report submitted.'});}catch(e){next(e)}}
 static async reports(req,res,next){try{res.json({reports:await Feature.reports(req.query.status||'open')});}catch(e){next(e)}}
 static async resolveReport(req,res,next){try{const row=await Feature.resolveReport(req.params.id,{adminId:req.user.id,status:req.body.status||'resolved',adminNote:req.body.adminNote||''});if(!row)return res.status(404).json({error:'Report not found.'});res.json({report:row});}catch(e){next(e)}}
 static async support(req,res,next){try{res.status(201).json({ticket:await Feature.createTicket(req.user.id,req.body.subject,req.body.message)});}catch(e){next(e)}}
 static async myTickets(req,res,next){try{res.json({tickets:await Feature.tickets(req.user.id)});}catch(e){next(e)}}
 static async allTickets(req,res,next){try{res.json({tickets:await Feature.allTickets(req.query.status||'')});}catch(e){next(e)}}
 static async updateTicket(req,res,next){try{const t=await Feature.updateTicket(req.params.id,req.body.status||'open',req.body.adminReply||'');if(!t)return res.status(404).json({error:'Ticket not found.'});res.json({ticket:t});}catch(e){next(e)}}
 static async ai(req,res,next){try{const env=require('../config/env');const mode=req.body.mode||'description';const title=String(req.body.title||'');const raw=String(req.body.input||'');if(!env.AI_API_URL||!env.AI_API_KEY)return res.json({configured:false,result:FeatureController.localAi(title,raw,mode)});const prompt=mode==='tags'?`Generate 6 concise comic genres/tags as a comma-separated list for ${title}. Synopsis: ${raw}`:`Write a polished 90-120 word comic synopsis for ${title}. Current notes: ${raw}`;const r=await fetch(env.AI_API_URL,{method:'POST',headers:{Authorization:`Bearer ${env.AI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:env.AI_MODEL||'default',messages:[{role:'user',content:prompt}],temperature:0.7})});const b=await r.json();if(!r.ok)throw new Error(b.error?.message||'AI provider request failed.');const result=b.choices?.[0]?.message?.content||b.output_text||b.output?.[0]?.content?.[0]?.text||'';res.json({configured:true,result});}catch(e){next(e)}}
 static localAi(title,input,mode){if(mode==='tags'){const s=(title+' '+input).toLowerCase();const tags=['Action','Adventure','Fantasy','Mystery','Romance','Sci-Fi','Supernatural','Drama','Comedy','Horror'].filter((x)=>s.includes(x.toLowerCase()));return (tags.length?tags:['Action','Fantasy','Drama']).slice(0,6).join(', ');}return `${title||'This comic'} follows a compelling journey shaped by ${input||'mystery, conflict, and unexpected choices'}. As the story unfolds, the characters face escalating challenges, hidden truths, and difficult decisions that change what they believe about the world around them. The series blends strong character moments with visual storytelling, memorable encounters, and a growing central mystery. Each chapter moves the story forward while introducing new questions and discoveries.`}
}
module.exports=FeatureController;
