document.addEventListener('DOMContentLoaded',async()=>{
 if(!Auth.isLoggedIn()){location.href='/login.html';return;}
 renderNavbar('platform');renderFooter();
 const $=id=>document.getElementById(id);
 const toast=(m,t='success')=>typeof showToast==='function'&&showToast(m,t);
 async function loadStreak(){const r=await API.post('/platform/streak/checkin',{markRead:false});const s=r.streak||{};$('streak').innerHTML=`<div class="streak-box"><div class="streak-number">${s.current_streak||0} 🔥</div><div style="flex:1"><strong>Current streak</strong><div class="progress-line"><span style="width:${Math.min(100,(s.current_streak||0)/7*100)}%"></span></div><span class="muted">Longest: ${s.longest_streak||0} days · Total reading days: ${s.total_read_days||0}</span></div></div>`}
 async function loadAchievements(){const r=await API.get('/platform/achievements');$('achievements').innerHTML=(r.achievements||[]).map(a=>`<div class="achievement ${a.earned_at?'earned':''}"><i class="fas ${a.icon||'fa-award'}"></i><strong>${a.name}</strong><div class="muted">${a.description}</div>${a.earned_at?'<small>✓ Earned</small>':''}</div>`).join('')||'<span class="muted">No achievements yet.</span>'}
 async function loadLists(){const r=await API.get('/platform/lists');$('lists').innerHTML=(r.lists||[]).map(l=>`<div class="mini-item"><div style="flex:1"><strong>${l.name}</strong><div class="muted">${l.item_count||0} comics ${l.is_public?'· Public':''}</div></div><button class="btn btn-secondary btn-sm del-list" data-id="${l.id}"><i class="fas fa-trash"></i></button></div>`).join('')||'<span class="muted">Create a list like “Read Later”, “Favorites”, or “Weekend Reads”.</span>';document.querySelectorAll('.del-list').forEach(b=>b.onclick=async()=>{await API.delete('/platform/lists/'+b.dataset.id);loadLists();})}
 async function discover(type='recommendations'){const r=await API.get('/platform/discover/'+type);$('discover').innerHTML=(r.items||[]).slice(0,8).map(c=>`<a class="mini-item" href="/comic.html?id=${encodeURIComponent(c.id)}"><img src="${c.cover_image||c.coverImage||'/uploads/covers/default.jpg'}"><div><strong>${c.title}</strong><div class="muted">${Number(c.views||0).toLocaleString()} views</div></div></a>`).join('')||'<span class="muted">Read and follow more comics to personalize this feed.</span>'}
 async function loadPrefs(){const [p,s]=await Promise.all([API.get('/platform/reader/preferences'),API.get('/auth/me')]);const x=p.preferences||{};$('reading-mode').value=x.reading_mode||'vertical';$('fit-mode').value=x.fit_mode||'width';$('image-quality').value=x.image_quality||'high';$('auto-scroll').checked=!!x.auto_scroll;$('bio').value=s.user?.bio||'';const a=s.user?.accessibility_settings||{};$('font-scale').value=String(a.fontScale||1);$('reduce-motion').checked=!!a.reduceMotion;$('high-contrast').checked=!!a.highContrast}
 async function loadNotify(){const r=await API.get('/platform/notifications/preferences');const p=r.preferences||{};$('notification-settings').innerHTML=['emailEnabled:Email notifications','newChapterEmail:New chapters','newFollowerEmail:New followers','commentEmail:Comments/replies','achievementEmail:Achievements'].map(x=>{const [k,l]=x.split(':');return `<label class="switch-row"><input type="checkbox" data-notify="${k}" ${p[k.replace(/[A-Z]/g,m=>`_${m.toLowerCase()}`)]!==false?'checked':''}> ${l}</label>`}).join('')+'<button class="btn btn-primary btn-sm" id="save-notify">Save Notifications</button>';$('save-notify').onclick=async()=>{const b={};document.querySelectorAll('[data-notify]').forEach(x=>b[x.dataset.notify]=x.checked);await API.put('/platform/notifications/preferences',b);toast('Notification preferences saved.');}}
 async function loadSecurity(){const r=await API.get('/platform/sessions');$('security').innerHTML=`<div class="security-actions"><button class="btn btn-secondary btn-sm" id="setup2fa"><i class="fas fa-key"></i> Setup 2FA</button><button class="btn btn-secondary btn-sm" id="refresh-sessions"><i class="fas fa-rotate"></i> Refresh Sessions</button></div><div id="session-list" style="margin-top:.8rem">${(r.sessions||[]).map(s=>`<div class="session"><div><strong>${s.device_name}</strong><div class="muted">${s.user_agent||''}</div></div>${!s.revoked_at?`<button class="btn btn-secondary btn-sm revoke" data-id="${s.id}">Revoke</button>`:'<span class="muted">Revoked</span>'}</div>`).join('')||'<span class="muted">No sessions recorded yet.</span>'}</div>`;document.querySelectorAll('.revoke').forEach(b=>b.onclick=async()=>{await API.delete('/platform/sessions/'+b.dataset.id);loadSecurity()});$('setup2fa').onclick=async()=>{const r=await API.post('/platform/2fa/setup',{});prompt('Save this authenticator secret, then enter the 6-digit code to enable 2FA:',r.secret);const code=prompt('Authenticator code:');if(code){await API.post('/platform/2fa/verify',{code});toast('Two-factor authentication enabled.');loadSecurity();}}}
 $('checkin').onclick=async()=>{await API.post('/platform/streak/checkin',{markRead:true});toast('Reading streak updated 🔥');loadStreak();loadAchievements()};
 $('new-list').onclick=async()=>{const name=prompt('Reading list name:','Read Later');if(name){await API.post('/platform/lists',{name});toast('Reading list created.');loadLists()}};
 document.querySelectorAll('[data-discover]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');discover(b.dataset.discover)});
 $('reader-form').onsubmit=async e=>{e.preventDefault();await API.put('/platform/reader/preferences',{readingMode:$('reading-mode').value,fitMode:$('fit-mode').value,imageQuality:$('image-quality').value,autoScroll:$('auto-scroll').checked});toast('Reader preferences saved.')};
 $('access-form').onsubmit=async e=>{e.preventDefault();await API.put('/platform/settings',{bio:$('bio').value,accessibility:{fontScale:Number($('font-scale').value),reduceMotion:$('reduce-motion').checked,highContrast:$('high-contrast').checked}});document.documentElement.style.fontSize=`${Number($('font-scale').value)*100}%`;document.body.classList.toggle('reduce-motion',$('reduce-motion').checked);document.body.classList.toggle('high-contrast',$('high-contrast').checked);toast('Accessibility settings saved.')};
 try{await Promise.all([loadStreak(),loadAchievements(),loadLists(),discover(),loadPrefs(),loadNotify(),loadSecurity()]);await API.post('/platform/sessions',{deviceName:'Current Browser'}).catch(()=>{});}catch(e){toast(e.message,'error')}
});