document.addEventListener('DOMContentLoaded',async()=>{document.body.classList.add('reader-page-body');const p=new URLSearchParams(location.search),chapterId=p.get('id');let requested=Math.max(1,parseInt(p.get('page')||'1',10));if(!chapterId)return location=sitePath('comics.html');const container=document.getElementById('reader-pages'),progress=document.getElementById('reader-progress'),pill=document.getElementById('page-pill');let chapter,all=[],page=1,mode=localStorage.getItem('ev-reader-mode')||'single',zoom=Number(localStorage.getItem('ev-reader-zoom')||1),saveTimer=null;
function applyMode(){container.dataset.mode=mode;container.style.setProperty('--reader-zoom',zoom);document.getElementById('reader-mode-btn').title=mode==='single'?'Switch to double page':'Switch to vertical fit';}
function scheduleSave(){if(!Auth.isLoggedIn()||!chapter)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>API.post('/users/me/history',{comicId:chapter.comicId,chapterId:chapter.id,pageNumber:page}).catch(()=>{}),1200);}
try{const r=await API.get(`/chapters/${encodeURIComponent(chapterId)}`);chapter=r.chapter;all=r.allChapters||[];document.title=`${chapter.title||'Chapter '+chapter.chapterNumber} — Elder's Veil`;const title=document.getElementById('reader-comic-title');const ct=document.getElementById('reader-chapter-title');if(title)title.textContent=chapter.comicTitle||chapter.title||`Chapter ${chapter.chapterNumber}`;if(ct)ct.firstChild.textContent=`Ch. ${chapter.chapterNumber} `;const select=document.getElementById('chapter-selector');select.innerHTML=all.map(x=>`<option value="${x.id}" ${x.id===chapter.id?'selected':''}>Chapter ${x.chapterNumber}: ${x.title||''}</option>`).join('');select.onchange=e=>location=`/reader.html?id=${e.target.value}`;const pages=chapter.pages||[];container.innerHTML=pages.length?pages.map((u,i)=>`<div class="reader-image-wrap" id="page-${i+1}" data-page="${i+1}"><img src="${u}" class="reader-image" alt="Page ${i+1}" loading="${i<2?'eager':'lazy'}"></div>`).join(''):'<div style="padding:5rem;text-align:center">No pages uploaded yet.</div>';page=Math.min(requested,Math.max(1,pages.length));applyMode();if(requested>1)setTimeout(()=>document.getElementById(`page-${page}`)?.scrollIntoView({block:'start'}),100);EVTrack?.('reader_open',{comicId:chapter.comicId,chapterId:chapter.id});
const curr=all.findIndex(x=>x.id===chapter.id),prev=curr>0?all[curr-1]:null,next=curr<all.length-1?all[curr+1]:null;document.getElementById('reader-nav-footer').innerHTML=`<button class="btn btn-secondary" ${!prev?'disabled':''} data-nav="prev"><i class="fas fa-chevron-left"></i> Previous Chapter</button><button class="btn btn-primary" ${!next?'disabled':''} data-nav="next">Next Chapter <i class="fas fa-chevron-right"></i></button>`;document.querySelector('[data-nav="prev"]').onclick=()=>prev&&(location=`/reader.html?id=${prev.id}`);document.querySelector('[data-nav="next"]').onclick=()=>next&&(location=`/reader.html?id=${next.id}`);
const setPage=()=>{const mid=innerHeight/2;document.querySelectorAll('.reader-image-wrap').forEach(el=>{const r=el.getBoundingClientRect();if(r.top<=mid&&r.bottom>=mid){const n=Number(el.dataset.page);if(n!==page){page=n;pill.textContent=`Page ${n} / ${pages.length}`;scheduleSave();}}});const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${Math.max(0,Math.min(100,scrollY/Math.max(1,max)*100))}%`;};addEventListener('scroll',setPage,{passive:true});setPage();
window.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;if(e.key==='ArrowLeft'&&prev)location=`/reader.html?id=${prev.id}`;if(e.key==='ArrowRight'&&next)location=`/reader.html?id=${next.id}`;if(e.key==='f')document.documentElement.requestFullscreen?.();if(e.key==='+'||e.key==='='){zoom=Math.min(2,zoom+.1);applyMode();localStorage.setItem('ev-reader-zoom',zoom)}if(e.key==='-'){zoom=Math.max(.6,zoom-.1);applyMode();localStorage.setItem('ev-reader-zoom',zoom)}});
document.getElementById('zoom-in').onclick=()=>{zoom=Math.min(2,zoom+.1);applyMode();localStorage.setItem('ev-reader-zoom',zoom)};document.getElementById('zoom-out').onclick=()=>{zoom=Math.max(.6,zoom-.1);applyMode();localStorage.setItem('ev-reader-zoom',zoom)};document.getElementById('reader-mode-btn').onclick=()=>{mode=mode==='single'?'double':mode==='double'?'vertical':'single';applyMode();localStorage.setItem('ev-reader-mode',mode)};document.getElementById('fullscreen-btn').onclick=()=>document.documentElement.requestFullscreen?.();
let tx=0;container.addEventListener('touchstart',e=>tx=e.changedTouches[0].clientX,{passive:true});container.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-tx;if(Math.abs(dx)>70){if(dx>0&&prev)location=`/reader.html?id=${prev.id}`;if(dx<0&&next)location=`/reader.html?id=${next.id}`;}},{passive:true});
}catch(e){container.innerHTML=`<div style="padding:5rem;text-align:center"><h3>Unable to load chapter</h3><p>${e.message}</p></div>`;}}
);
